# pytest.ini
[pytest]
# Add the current directory to PYTHONPATH to ensure 'cda' is discoverable
pythonpath = .
# Set the directory where tests are located
testpaths = cda/tests
# Log level for more detailed output
log_cli = true
log_cli_level = INFO